### PR TITLE
Escapes option user HTML and fixes option key

### LINKED ISSUE #6: Escape single button option HTML
We are not escaping this option:

https://github.com/wpovernight/woocommerce-improved-external-products/blob/c79c2d64942a21cc892d5589b16b4f0342684321/wc-improved-external-products.php#L162

And this key is also wrong:

https://github.com/wpovernight/woocommerce-improved-external-products/blob/c79c2d64942a21cc892d5589b16b4f0342684321/wc-improved-external-products.php#L160

### PR DESCRIPTION
**Pull request by alexmigf**
closes #6

Included `alex` in classes:

Captura de ecrã de 2022-10-07 08-53-36

Frontend output:

Captura de ecrã de 2022-10-07 08-54-39

### CODE REVIEW

File: wc-improved-external-products.php [hunk 1]
```diff
@@ -157,13 +158,13 @@ function iepp_external_add_to_cart() {
...
 
 		<?php
-		$options = get_option('improvedexternalproducts');
-		if(!empty($options['custom_single_button_html'])){
-			$html = $options['custom_single_button_html'];
-			$html = str_replace('{product_url}', esc_url( $product_url ), $html);
-			$html = str_replace('{target}', $target, $html);
-			$html = str_replace('{button_text}', esc_html( $button_text ), $html);
-			$html = str_replace('{price_html}', $price_html, $html);
+		$options = get_option('woocommerce-improved-external-products');
```
Comment (DavidAnderson684) [inline wc-improved-external-products.php:161]: @alexmigf This implies that before it was buggy, fetching the option from the wrong place? So apparently nobody is using the feature, if nobody noticed?

Comment (alexmigf) [reply wc-improved-external-products.php:161]: After discussing this with Ewout, which did this code 4 years ago, it seems a long time bug that no one haven't discovered to date. Because the Pro version uses the removed key, maybe some confusion happened at the time.

**Review by DavidAnderson684 — APPROVED** [review]
